# **Tarea de Numpy**

Este notebook es el de los ejercicios >:)


In [88]:
!pip install numpy
import numpy as np

# Probando si si jala el numpy
my_arreglow = np.array([1, 2, 3, 4, 5])

print(my_arreglow)
print(np.mean(my_arreglow))
# mean nos da el promedio del arreglo


[1 2 3 4 5]
3.0


## Ejercicios de refuerzo

### **Ejercicio 1 - Crear un array de ceros:**
Crea un array de tamaño (3, 4) lleno de ceros.

In [89]:
A = np.zeros((3, 4))
A

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### **Ejercicio 2-  Suma de elementos:**
   Dado el array [1, 2, 3, 4, 5], calcula la suma de todos sus elementos usando NumPy.

In [90]:
a = np.sum(A)
a

np.float64(0.0)

### **Ejercicio 3 - Encontrar el máximo y mínimo:**
Dado el array [10, 20, 30, 40, 50], encuentra el valor máximo y mínimo.

In [91]:
array = np.array([10, 20, 30, 40, 50])
min = np.min(array)
max = np.max(array)
print("Para el array {}, el valor mínimo es {} y el maximo es {}".format(array, min, max))


Para el array [10 20 30 40 50], el valor mínimo es 10 y el maximo es 50


### **Ejercicio 4 - Encontrar el máximo y mínimo:**
 Dado el array [10, 20, 30, 40, 50], encuentra el valor máximo y mínimo.


In [92]:
#Este es el mismo ejercicio que el 3
print("Para el array {}, el valor mínimo es {} y el maximo es {}".format(array, np.min(array), np.max(array)))

Para el array [10 20 30 40 50], el valor mínimo es 10 y el maximo es 50


In [93]:
print("Para el array {}, el valor mínimo es {} y el maximo es {}".format(array, array.min(), array.max()))

Para el array [10 20 30 40 50], el valor mínimo es 10 y el maximo es 50


### **Ejercicio 5 - Generar números aleatorios:**
  Genera un array de 5 números aleatorios entre 0 y 1.

In [94]:
aleatorios = np.random.randint(1, 100, size=(3, 4))
aleatorios


array([[71, 72,  1, 28],
       [77, 94, 31, 92],
       [11, 68, 47, 54]])

In [95]:
np.random.rand(3, 4)
#Para numeros aleatorios entre 0 y 1

array([[0.8709659 , 0.59654094, 0.68431607, 0.60850895],
       [0.42562136, 0.62203447, 0.97174025, 0.5011501 ],
       [0.09381115, 0.95989353, 0.16494326, 0.37749846]])

### **Ejercicio 6 - Promedio de un array:**
Dado el array [5, 10, 15, 20, 25], calcula su promedio usando NumPy.

In [96]:
B = np.array([5,10,15,20,25])
print("El Promedio  de {} es {}".format(B,np.mean(B)))
#print("El promedio de {} es {}".format(B,np.sum(B)/len(B)))


El Promedio  de [ 5 10 15 20 25] es 15.0


### **Ejercicio 7 - Concatenar dos arrays**
Dados los arrays A = [1, 2, 3] y B = [4, 5, 6], concaténalos en un solo array.

In [97]:
A = np.array([1,2,3])
B = np.array([4,5,6])
np.concatenate((A, B))


array([1, 2, 3, 4, 5, 6])

### **Ejercicio 8 - Reshape de un Array**
Dado el array [1, 2, 3, 4, 5, 6], cámbialo a una matriz de 2x3.

In [98]:
D = np.array([1,2,3,4,5,6])
D.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

### **Ejercicio 9 - Producto punto (dot product):**
Dados dos arrays A = [1, 2, 3] y B = [4, 5, 6], calcula su producto punto

In [99]:
A = np.array([1,2,3])
B = np.array([4,5,6])
np.dot(A, B)

np.int64(32)

### **Ejercicio 10 - Reorganizar un array:**
Dado el array [1, 2, 3, 4, 5, 6, 7, 8, 9, 10], conviértelo en una matriz (2, 5).

In [100]:
E = np.array([1,2,3,4,5,6,7,8,9,10])
E.reshape(2, 5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

### **Ejercicio extra - Encontrar el *k*-ésimo elemento más pequeño en un array**
Dado arr = np.array([9, 3, 6, 2, 1, 7]), encuentra el 3er elemento más pequeño sin ordenar el array completo.

**Pista solución 1**: Se puede hacer con un método de Numpy

**Pista solución 2**: El código se hace más complicado, pero se puede resolver con ciclos iterativos.

In [101]:
#con np.partition(arreglo,k) podemos ordenar el arreglo hasta el k elemento
arr = np.array([9, 3, 6, 2, 1, 7])
np.partition(arr, 2)[2]


np.int64(3)

## **Ejercicios aplicados**

### **Ejercicio: Cálculo de ROI (Retorno de Inversión)**
Dadas las inversiones ([1000, 1500, 2000]) y sus retornos ([1200, 1650, 1800]), calcula el ROI porcentual para cada caso.

*(Fórmula: ROI = (retorno - inversión) / inversión * 100)*

In [102]:
# Solucion del ROIROIROIROIORIORI
inversiones = np.array([1000, 1500, 2000])
retorno = np.array([1200, 1650, 1800])
ROI = (retorno - inversiones) / inversiones * 100
ROI

array([ 20.,  10., -10.])

### **Ejercicio: Normalización de Datos**
Tienes un dataset de precios de productos (en USD): [250, 320, 150, 500, 210]. Normaliza los valores al rango [0, 1] para compararlos en una escala común.

**Formulita de la normalización**: (x - min) / (max - min): Para una escala valores entre 0 y 1.

In [103]:
X = np.array([250, 320, 150, 500, 210])
(X - X.min() )/ (X.max() - X.min())

array([0.28571429, 0.48571429, 0.        , 1.        , 0.17142857])

### **Ejercicio: Filtrado de Datos**
En un array de ventas diarias ([1200, 0, 750, 2400, 0, 1800]), reemplaza los ceros (días sin ventas) por el promedio de los días con ventas.

In [104]:
#Primero obtenemos el promedio de las ventas
# y luego sustituimos los ceros 
ventas = np.array([1200,0,750,2400,0,1800])
prom = np.mean(ventas)
ventas[ventas == 0] = prom
ventas

array([1200, 1025,  750, 2400, 1025, 1800])

### **Ejercicio - Análisis de Presión Arterial**
Tenemos un dataset de mediciones de presión arterial sistólica (mmHg) de 10 pacientes:
[120, 135, 140, 118, 150, 130, 160, 125, 142, 128].

Calculen:
- Media y desviación estándar.
- Identifiquen valores fuera del rango normal (90–140 mmHg).

In [105]:
PA = np.array([120,135,140,118,150,130,160,125,142,128])
media = np.median(PA)
desv = np.std(PA)
print("La media es {} y su desviación estandar es {:.2f}".format(media,desv))
#Usamos {:.2f} para que nos de solo dos decimales
#Ahora para filtrar los valores mayores a 140 y menores a 90
anormal = PA[(PA > 140) | (PA < 90)]
print("Los siguientes valores son anormales {}".format(anormal))


La media es 132.5 y su desviación estandar es 12.69
Los siguientes valores son anormales [150 160 142]


### **Ejercicio - Cálculo del PIB per Cápita**
Dados el PIB (en millones de USD) [500, 320, 700, 450] y la población (en millones) [10, 8, 12, 9] de 4 países, calculen el PIB per cápita y determinen el país con el mayor valor.

In [106]:
PIB = np.array([500, 320, 700, 450])
Pob = np.array([10, 8, 12, 9])
PIB_Percapita = PIB / Pob
print("El PIB per capita mas alto es {:.2f}".format(PIB_Percapita.max()))


El PIB per capita mas alto es 58.33


### **Ejercicio - Sistema de Drops (Probabilidades)**
En un videojuego RPG, los enemigos al ser vencidos, pueden dropear (soltar):
- 0 = Nada (50%).
- 1 = Poción (30%).
- 2 = Arma (15%).
- 3 = Artefacto (5%).

Simula 100 drops y cuenta cuántos artefactos se obtuvieron.

*Ejemplo de salida*:

```
Artifactos obtenidos: 3
```



In [107]:
drop = np.array([0, 1, 2, 3])
prob = np.array([0.5, 0.3, 0.15, 0.05])
#Podemos crear un array con 100 elementos de la lista drop con probabilidades prob usando random.choice
prueba_drops = np.random.choice(drop, size = 100, p = prob)

print("En la simulación de 100 drops, obtenemos {} artículos".format(prueba_drops.sum()))



En la simulación de 100 drops, obtenemos 94 artículos
